# Huge, MEE SUSTech
# Email: zhuhu00@foxmail.com

version: '2.3'
services:
  ubuntu18-ros-macm1:
    image: zhuhu/ubuntu18-ros-macm1:0.1
    build: .
    container_name: ubuntu18-ros-macm1

    command: terminator
    # command: lxterminal
    # runtime: nvidia
    privileged: true
    stdin_open: true
    tty: true
    environment:
        - DISPLAY=192.168.31.66:0
        - QT_X11_NO_MITSHM=1
    # devices:
        # - /dev:/dev

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # - ../../faster-lio:/root/catkin_ws/src/faster-lio
      # - ${DATASET_DIR}:/root/Dataset

    entrypoint: /ros_entrypoint.sh
    network_mode: host

# volumes:
#   cuda110-ros-ubuntu20: